#!/usr/bin/env bash
## -*- sh-basic-offset: 2 -*-

if [ ! -d "be-tree" ]; then
    git clone https://github.com/FrankBro/be-tree
    cd be-tree
    make
    mkdir -p ../priv
    cp build/libbetree.so ../priv/libbetree.so
fi

